maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/305_filtered_feature_bc_matrix/filtered_feature_bc_matrix/

projectName: "305"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/305_cellranger/

pattern: "^mt-"

multimodal: false

multiSampled: false

HTO: false

numberOfCells: 4302

sampleInputs:
  - name: 305-1
    mtCutoff: 10
    expectedPercentDoublets: 0.02
    dbElbowPlot: 17
    otherMetaData: Tag3
  - name: 305-2
    mtCutoff: 10
    expectedPercentDoublets: 0.01
    dbElbowPlot: 17
    otherMetaData: Tag3
  - name: 305-3
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    otherMetaData: Tag3
    dbElbowPlot: 17
  - name: 305-4
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: Tag7
  - name: 305-5
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: Tag7
  - name: 305-6
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: Tag7

otherMetaName: timepoint

integrationPCs: 30

findNeighborsPCs: 25

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.8

countIdents: [timepoint, orig.ident]
