HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/284_filtered_feature_bc_matrix/filtered_feature_bc_matrix/

projectName: "284"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/284_cellranger_2/

pattern: "^mt-"

multimodal: true

multiSampled: false

HTO: true

numberOfCells: 2625

sampleInputs:
  - name: 284-1
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 284-2
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 284-3
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 284-4
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 284-5
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 284-6
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]

otherMetaName: [condition]

integrationPCs: 30

findNeighborsPCs: 27

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.5

countIdents: [condition, orig.ident]
