HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/165_cellranger_aggr/filtered_feature_bc_matrix/

projectName: "165nm"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/165nm_cellranger/

mtPattern: "^mt-"

multimodal: false

multiSampled: true

HTO: false

numberOfCells: 66040

sampleInputs:
  - name: 165-1
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 165-2
    mtCutoff: 25
    expectedPercentDoublets: 0.11
    dbElbowPlot: 17
    otherMetaData: [sham]
  - name: 165-3
    mtCutoff: 25
    expectedPercentDoublets: 0.11
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 165-4
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 165-5
    mtCutoff: 25
    expectedPercentDoublets: 0.05
    dbElbowPlot: 17
    otherMetaData: [sham]
  - name: 165-6
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [sham]

otherMetaName: [condition]

integrationPCs: 30

findNeighborsPCs: 27

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.5
