#the following variables are usually filled during the run of the pipeline
# - chosenResolution
# - integrationPCs
# - findNeigborsPCs
# - mtCutoff
# - dbElbowPlot

HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 68719476736 #30GB RAM for IntegrationDimReduction, let X be the RAM you want in GB. Set maxRAM=X*1024^3

workDirectory: workDirectory/ #can stay this way for now

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/354_cellranger/ #the (absolute) path where the output folder is going to be

rawData: data/354_filtered_feature_bc_matrix/filtered_feature_bc_matrix/ #directory containing the cellranger outputs which serves as this pipelines input

pattern: "^MT-" #the mt-pattern for mitochondiral filtering

multimodal: false #whether input contains protein data or not

multiSampled: true #Does the file contain multiple samples, true for yes and false for no

HTO: false #whether this should be HTO demultiplex 

numberOfCells: 46000 #number of all cells in the input

projectName: 354_cellranger_aggr #the name of the project, if just a number please put it in ""

otherMetaName: [Donor] #condition name, e.g. timepoint

choosableResolutions: [0.5, 0.8] #list of resolutions for clustering, choose one after checking plots and fill out "chosenResolution"

chosenResolution: 0.5 #resolution for the clustering chosen from list, after checking plots ending with ".clusteredDimPlot.pdf"

integrationPCs: 19 #PCs/dimensions for running UMAP, check plot ending with ".integratedElbowPlot.pdf"

findNeighborsPCs: 19 #dimensions of reduction to use as input for SNN-Graph construction, check plot ending with ".umappedElbowPlot.pdf"


#when more than two samples, copy and paste the second point, unitl you can fill out the information for every sample
sampleInputs:
  - name: 10X_Sample3 #name of the sample in cellranger, possible pattern: project_number-1, project_number-2, ..., project_number-n
    otherMetaData: [HC1] #name of condition value, for timepoint example, here day1, next sample day1, sample after that day5, ...
    expectedPercentDoublets: 0.05 #expected percent of doublets, is dependent on the number of cells in a sample
    mtCutoff: 100 #percentage cutoff chosen during pipeline run -> e.g., 10, remove all cells with more than 10% mitochondrial counts,
              #check plots ending with ".mt.before.pdf"
    dbElbowPlot: 15 #PCs/dimensions chosen from plots for doublet removal, check plots ending with ".ElbowPlot.pdf"
  - name: 10X_Sample10
    otherMetaData: [HC1]
    expectedPercentDoublets: 0.09
    mtCutoff: 100
    dbElbowPlot: 15
  - name: 10X_Sample5
    otherMetaData: [PD2]
    expectedPercentDoublets: 0.09
    mtCutoff: 100
    dbElbowPlot: 15
  - name: 10X_Sample6
    otherMetaData: [PD2]
    expectedPercentDoublets: 0.09
    mtCutoff: 100
    dbElbowPlot: 15
