HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/215_cellranger_aggr/filtered_feature_bc_matrix/

projectName: "215"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/215_cellranger/

mtPattern: "^mt-"

multimodal: false

multiSampled: true

HTO: false

numberOfCells: 13228

sampleInputs:
  - name: 157-1
    mtCutoff: 10
    expectedPercentDoublets: 0.02
    dbElbowPlot: 17
    otherMetaData: [Tag3]
  - name: 215-1
    mtCutoff: 10
    expectedPercentDoublets: 0.01
    dbElbowPlot: 17
    otherMetaData: [Tag3]
  - name: 215-2
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    otherMetaData: [Tag3]
    dbElbowPlot: 17
  - name: 215-3
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: [Tag7]
  - name: 215-4
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: [Tag7]
  - name: 215-5
    mtCutoff: 10
    expectedPercentDoublets: 0.016
    dbElbowPlot: 17
    otherMetaData: [Tag7]

otherMetaName: [timepoint]

integrationPCs: 30

findNeighborsPCs: 25

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.8