HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/305_filtered_feature_bc_matrix/filtered_feature_bc_matrix/

projectName: "305_165"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/305_cellranger_2/

mtPattern: "^mt-"

multimodal: false

multiSampled: false

HTO: false

numberOfCells: 4302

sampleInputs:
  - name: 305-1
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]

otherMetaName: [condition]

integrationPCs: 30

findNeighborsPCs: 27

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.5
