HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/244_filtered_feature_bc_matrix/filtered_feature_bc_matrix/

projectName: "244"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/244_cellranger_2/

pattern: "^mt-"

multimodal: false

multiSampled: true

HTO: false

numberOfCells: 66723

sampleInputs:
  - name: 244-1
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 244-2
    mtCutoff: 25
    expectedPercentDoublets: 0.11
    dbElbowPlot: 17
    otherMetaData: [sham]
  - name: 244-3
    mtCutoff: 25
    expectedPercentDoublets: 0.11
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 244-4
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]
  - name: 244-5
    mtCutoff: 25
    expectedPercentDoublets: 0.05
    dbElbowPlot: 17
    otherMetaData: [sham]
  - name: 244-6
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [sham]

otherMetaName: [condition]

integrationPCs: 30

findNeighborsPCs: 27

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.5

countIdents: [condition, orig.ident]
