HHU_HPC: true #if this is used on the HHU HPC Hilbert 

maxRAM: 32212254720 #30GB RAM

workDirectory: workDirectory/

rawData: data/143_filtered_feature_bc_matrix/filtered_feature_bc_matrix/

projectName: "143_165ms"

projectDirectoryPath: /scratch_gs/myhuy100/projects_experimental/143ms_cellranger_2/

pattern: "^mt-"

multimodal: true

multiSampled: false

HTO: false

numberOfCells: 7757

sampleInputs:
  - name: 143-1
    mtCutoff: 25
    expectedPercentDoublets: 0.075
    dbElbowPlot: 17
    otherMetaData: [Ablation]

otherMetaName: [condition]

integrationPCs: 30

findNeighborsPCs: 27

choosableResolutions: [0.5, 0.8, 0.7]

chosenResolution: 0.5
